name: finmene
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  tflite_flutter: ^0.11.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
